name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Debug Application for linux
      run: ./build.sh

    - name: Build Release Application for linux
      run: ./buildRelease.sh
