name: macOS

on: push
jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Debug Application for macOS
      run: ./build.sh

    - name: Build Release Application for macOS
      run: ./buildRelease.sh
