name: Windows

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: Build Debug Application For Windows.
      run: |
        cmake -DCMAKE_BUILD_TYPE=Debug .
        dir
        msbuild MouseEditor.sln
        dir

    - name: Build Release Application For Windows.
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release .
        dir
        msbuild MouseEditor.sln
        dir
